title: Joe (승현) Lee # name of the site
author: Joe Lee # name of site's author
email: # email of site's author
url: https://sehyunlee217.github.io # root address of the site
baseurl: # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)

permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "back" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jektex
  - jekyll-redirect-from

jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block_code_attr: 'class="highlight"'

exclude:
  - vendor/
  - vendor/bundle/
  - .jekyll-cache/
  - .jektex-cache/
  - _site/
  - Gemfile
  - Gemfile.lock
